import { redirect } from "next/navigation";
import { validateRequest } from "@/auth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await validateRequest();
  if (user) {
    return redirect("/");
  }
  return <>{children}</>;
}
