import { Metadata } from "next";

import { db } from "@/db";
import { projectTable } from "@/db/schema";
import { eq } from "drizzle-orm";
import { RedirectType, redirect } from "next/navigation";
export const metadata: Metadata = {
  title: "Project Page",
  description: "Generated by create next app",
};
import { createVM, deleteVM } from "@/utils/awsOps";

export default async function Layout({
  children,
  params: { project },
}: {
  children: Readonly<{
    children: React.ReactNode;
  }>;
  params: { project: string };
}) {
  console.log({ project });

  const info = await db
    .select()
    .from(projectTable)
    .where(eq(projectTable.id, project));
  if (info.length === 0) {
    redirect("/");
  }

  const status = await createVM(info[0].id, info[0].userId, info[0].template);
  if (!status) {
    redirect("/");
  }
  return <>{children}</>;
}
